// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPcse7LAihhAFvzln9GRcyP6qk-_bTNVg',
    appId: '1:126308261052:web:53ab4048282f4f808a04b9',
    messagingSenderId: '126308261052',
    projectId: 'instagram-flutter-clone-769c0',
    authDomain: 'instagram-flutter-clone-769c0.firebaseapp.com',
    storageBucket: 'instagram-flutter-clone-769c0.firebasestorage.app',
    measurementId: 'G-SFH0FJ1EE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpeK0qvh6I3dfHgP9ZLP0N-5IOeGVdv8',
    appId: '1:126308261052:android:259bb5dd24f18db68a04b9',
    messagingSenderId: '126308261052',
    projectId: 'instagram-flutter-clone-769c0',
    storageBucket: 'instagram-flutter-clone-769c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWr96mYE-bl0qy2jKDzFYcuVkrCbmwzTc',
    appId: '1:126308261052:ios:b86c61995a2020de8a04b9',
    messagingSenderId: '126308261052',
    projectId: 'instagram-flutter-clone-769c0',
    storageBucket: 'instagram-flutter-clone-769c0.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWr96mYE-bl0qy2jKDzFYcuVkrCbmwzTc',
    appId: '1:126308261052:ios:b86c61995a2020de8a04b9',
    messagingSenderId: '126308261052',
    projectId: 'instagram-flutter-clone-769c0',
    storageBucket: 'instagram-flutter-clone-769c0.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutterClone',
  );

}